### ISSUE TITLE
Fichier 50, erreur dans la signature de la fonction flushes

### ISSUE THREAD

**Issue by ubourdon** [ToF-/SlicesOfFP#3]
https://github.com/ToF-/SlicesOfFP/blob/master/code/050.hs

L'ordre des paramètres de la fonction `flushes` sont inversés entre la signature et l'implémentation.

**Comment by ubourdon** [comment]
Il y a aussi un soucis dans l'implémentation du dernier cas de pattern matching de la de la fonction `flushes`.

**Comment by ToF-** [comment]
Merci Ugo pour ton attention et ton temps. Tes retours sont précieux!

**Comment by ubourdon** [comment]
Pas de soucis. Ça me fait plaisir de participer. Ce kata est vraiment bien et votre approche "TDD" vraiment appréciable pour apprendre Haskell.
