### ISSUE TITLE
Pourquoi flushes prend un Bool en rentrée ?

### ISSUE THREAD

**Issue by ubourdon** [ToF-/SlicesOfFP#4]
https://github.com/ToF-/SlicesOfFP/blob/master/code/Specs.hs#L58

On peut "mentir" à la fonction `isFlush` via la Boolean non ?

Cela montre-t-il un soucis de design ? Peut on l'améliorer ?

**Comment by ToF-** [comment]
Dans un projet "normal", on exposerait pas `flushes` au niveau public, elle serait une auxiliaire de `ranking` (i.e. declarée dans une clause `where` dans l'implémentation de `ranking`).
Pas d'accès public => pas de besoin de "garder" la fonction.

Ma "règle du pouce" est de ne faire du défensif qu'à la surface d'une A.P.I. 
À l'intérieur de ce module, il n'est pas possible de tromper `flushes`.
