### ISSUE TITLE
final ranking function not compile

### ISSUE THREAD

**Issue by ubourdon** [ToF-/SlicesOfFP#5]
https://github.com/ToF-/SlicesOfFP/blob/master/code/Specs.hs#L68
A priori la fonction ranking dans le dernier fichier de solution ne compile pas.
Je pense que l'appel à `ranks` est en trop.

```haskell
ranking :: [Card] -> Ranking
ranking cs = flushes (isFlush cs) (promote (cat, rs))
    where
    cat = category gs
    rs  = concat   gs
    gs = groups (ranks cs)
```

**Comment by ToF-** [comment]
gs = groups cs

merci!
